version: "3.4"
services:
  frontend:
    container_name: shelf-sharks-frontend
    image: shelf-sharks-frontend
    build:
      context: Shelf-Sharks.WebApp
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production

  backend:
    container_name: shelf-sharks-backend
    image: shelf-sharks-backend
    build:
      context: Shelf-Sharks.WebApi
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production

networks:
  default:
    external:
      name: nginx-proxy_default
